services:
  coturn:
    image: coturn/coturn:4.6
    restart: unless-stopped
    network_mode: host
    command:
      - "-n"
      - "--log-file=stdout"
      - "--lt-cred-mech"
      - "--realm=solace.local"
      - "--user=solace:solace"
      - "--fingerprint"
      - "--no-tls"
      - "--no-dtls"
      - "--no-multicast-peers"
      - "--min-port=50000"
      - "--max-port=50999"
      - "--stale-nonce=600"
      - "--listening-port=3478"
      - "--log-binding"
      - "--external-ip=167.233.63.56"
      - "--no-cli"
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: "0.25"
          pids: 64